<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filter by Entidad Seguro_tabviewaddCu_0fe1cf</name>
   <tag></tag>
   <elementGuidId>51b2a006-8a64-4e67-95aa-5dc8a5f33466</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Filter by Entidad Seguro&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>946136af-36d8-43fc-93e4-20314743c799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter</value>
      <webElementGuid>f1b33a20-521d-4833-b766-10cc1194dfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter</value>
      <webElementGuid>531b014e-a3dc-4043-a9ff-e6dc5baaff37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>90875aac-c330-4e39-b7e4-f08d405c6ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e2dd1353-abf1-4925-9d0e-db1441268587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter_label</value>
      <webElementGuid>68eea0a2-be9c-4d59-bdef-06d0256ab491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>df90bab5-f63b-4b27-8814-ee112c5af20c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b53b3139-b42e-4fdf-bc7f-b6591c007d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>61672633-e440-4aa6-9d9b-99a374068ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter&quot;)</value>
      <webElementGuid>ff74897f-b1b5-4905-a8dd-f1fc832c06c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/creacion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>6afa5cef-cba6-4dc9-9926-9a3db9183cfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter']</value>
      <webElementGuid>570f6e55-9bd2-472c-966c-ce3313a0337f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775']/input</value>
      <webElementGuid>c4d9a774-f475-4231-9024-cf233721bb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/thead/tr/th/input</value>
      <webElementGuid>303e4460-afbd-4a4a-a1e1-804f6caac4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter' and @name = 'tabview:addCuposForm:tblEntidadSeguroCupos:j_idt775:filter']</value>
      <webElementGuid>bef92625-bab3-4c61-9244-44776d5010b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
