<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione</name>
   <tag></tag>
   <elementGuidId>8269e6dc-d36e-4954-9b22-0b5b37ed16db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='tabview:addCuposForm:tipoRangoCombo_label']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;tabview\:addCuposForm\:tipoRangoCombo_label&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63d00685-a64d-4a5e-ab82-5bdc293fa93a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:tipoRangoCombo_label</value>
      <webElementGuid>ddf0d5ad-31dd-47c6-80d6-37c7ffb7cf5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>74416466-bac1-40b7-a6ea-3c53858ae9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione</value>
      <webElementGuid>42174706-bed7-4c84-bcc4-8263b9c1a5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:tipoRangoCombo_label&quot;)</value>
      <webElementGuid>4d6c26f3-6e20-4991-917a-705ca4aa3a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Agendamiento cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>b0de6a15-f6b0-4ef4-83a1-cb9c08c9f1ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='tabview:addCuposForm:tipoRangoCombo_label']</value>
      <webElementGuid>cf333539-597c-4019-b375-88b67b4315be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabview:addCuposForm:tipoRangoCombo']/label</value>
      <webElementGuid>921fa6bc-2dad-4a90-833f-4d268755b33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intervalo'])[1]/following::label[1]</value>
      <webElementGuid>3b7073bf-8ba3-4236-8543-1a70c20f0755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[24]/following::label[1]</value>
      <webElementGuid>6d6d169b-d63f-4df1-a387-0d7ea8f9d1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rango(minutos)'])[1]/preceding::label[1]</value>
      <webElementGuid>18366569-ba2a-4779-a02d-2b89bbd48dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subactividad'])[1]/preceding::label[1]</value>
      <webElementGuid>86a8599e-0b32-4a27-ae92-7cabfb446680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td[2]/div/label</value>
      <webElementGuid>c4108989-dd62-4837-bf44-f56872fea187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'tabview:addCuposForm:tipoRangoCombo_label' and (text() = 'Seleccione' or . = 'Seleccione')]</value>
      <webElementGuid>eb2ed03b-81b0-48ef-9043-e5c3b4b588ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
