<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Historia Clinica</name>
   <tag></tag>
   <elementGuidId>8dda2951-c03f-4700-8a0f-93970b34f5ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form:carrousel:0:treetableCalendar:0_0:j_idt344']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>button[name=&quot;form\:carrousel\:0\:treetableCalendar\:0_0\:j_idt344&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68477397-b963-46b4-a482-36d61f3b5160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:carrousel:0:treetableCalendar:0_0:j_idt344</value>
      <webElementGuid>85d2c814-a1d3-47bb-a9bb-9b71c5c9dd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:carrousel:0:treetableCalendar:0_0:j_idt344</value>
      <webElementGuid>4b4f3e57-6892-4b02-9b22-1a862e4438b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-state-focus ui-state-hover</value>
      <webElementGuid>70745281-d224-4a29-96b9-8d00bd530b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form:carrousel:0:treetableCalendar:0_0:j_idt344&quot;,f:&quot;form&quot;,u:&quot;form:carrousel:0:treetableCalendar:0_0:colRowCita form historiaPacienteForm form:carrousel:0:treetableCalendar:0_0:colRowCita&quot;,rv:true});return false;</value>
      <webElementGuid>00d2ae8c-cbf9-445e-bd25-f0e75c66cf08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Historia Clinica</value>
      <webElementGuid>7642136f-baf0-4e45-9503-836fb9a22963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a6bb1f02-446b-43be-b4ac-0c154d56cc41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0414d016-4dca-4b1a-9f07-4c6fd3bf318f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c90ed95e-c95d-406a-84f3-ecec397ba7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Historia Clinica</value>
      <webElementGuid>40cfc786-c0b0-44e4-afb1-5770b9c6190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:carrousel:0:treetableCalendar:0_0:j_idt344&quot;)</value>
      <webElementGuid>562d2737-fb2c-4dc3-8e67-a6e280f6ee1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>7b532221-28c3-4353-9e81-5083a1e15564</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form:carrousel:0:treetableCalendar:0_0:j_idt344']</value>
      <webElementGuid>facc28bb-2ad5-426b-8679-cc5d47199037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='form:carrousel:0:treetableCalendar_node_0_0']/td/div/button</value>
      <webElementGuid>c86c70d0-c182-4af6-a9e7-4e3fec6b8f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOGOTA      PRIMERA VEZ'])[1]/following::button[1]</value>
      <webElementGuid>1ec7595c-82e3-457d-8e81-e761b08a9180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En sala'])[1]/following::button[1]</value>
      <webElementGuid>90d4b84e-6645-4a80-bb01-f42c025b7d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta archivo asociado a la cita'])[1]/preceding::button[1]</value>
      <webElementGuid>6df6ff01-3eb2-4bcf-ba8c-327425c3ef4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td/div/button</value>
      <webElementGuid>70187920-7f40-49a3-8b8f-aba72c59575d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'form:carrousel:0:treetableCalendar:0_0:j_idt344' and @name = 'form:carrousel:0:treetableCalendar:0_0:j_idt344' and @title = 'Historia Clinica' and @type = 'submit' and (text() = 'Historia Clinica' or . = 'Historia Clinica')]</value>
      <webElementGuid>d7e949fb-8af5-4516-9e44-047b15874e16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
