<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar</name>
   <tag></tag>
   <elementGuidId>071676ba-03d3-4134-bed1-4a0da49ed32c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cancelarCitaForm']//button[contains(@class, 'ui-button') and .//span[@class='ui-button-text ui-c' and text()='Guardar']]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>677c1dd7-70da-45b6-bb68-0c4c5b53e478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelarCitaForm:j_idt620</value>
      <webElementGuid>b4cfa251-d9c9-488e-b814-f0b5d6770cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cancelarCitaForm:j_idt620</value>
      <webElementGuid>ebdf9f37-db23-4ff3-818c-89fbc4fba31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-state-focus ui-state-hover</value>
      <webElementGuid>ff7a9641-58ec-4b64-bcf9-0967b20f0673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;cancelarCitaForm:j_idt620&quot;,f:&quot;cancelarCitaForm&quot;,u:&quot;@(#form\\:carrousel :not(.noupdate)) form:growl pacienteCitasForm formMenuCampana2 txtNovistos2&quot;,onco:function(xhr,status,args,data){handleSubmit(xhr,status,args,PF('CancelarCitaDialog'));;}});return false;</value>
      <webElementGuid>b29bd5d7-f229-4835-9c1b-3b31c434a80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>712dca56-3e94-42a6-bafc-abe126bcbd10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c288ccd4-7e80-4745-a413-794df2424f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2effefb9-01f9-449e-925b-c163769f9e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>484a0172-3e32-47ac-98ea-b45b6c315d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelarCitaForm:j_idt620&quot;)</value>
      <webElementGuid>00f3f4a4-a186-481e-8f30-3062f08abe02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>f0f35b52-d1bb-4e94-b40d-419a7f8e41c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cancelarCitaForm:j_idt620']</value>
      <webElementGuid>c632bb22-ae47-4b9b-849c-b4ce66a1dd03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cancelarCitaForm:j_idt617_content']/div[2]/div/button</value>
      <webElementGuid>3d385b55-8f2f-4e31-b4c5-efc09873eba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar Correo de Cancelación'])[1]/following::button[1]</value>
      <webElementGuid>083405c6-56a4-43e0-aedb-f380e7b3e75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCIDENTE'])[2]/following::button[1]</value>
      <webElementGuid>33dba3bf-fc5c-42cd-b198-33bc0f055633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[5]/preceding::button[1]</value>
      <webElementGuid>e457cb93-bda2-4409-b613-bed66924beb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/button</value>
      <webElementGuid>a5b794b7-fbf6-4110-b72b-1fe07933b344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cancelarCitaForm:j_idt620' and @name = 'cancelarCitaForm:j_idt620' and @type = 'submit' and (text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>5a801fde-ee47-4e5e-b62b-6fc872595e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
