<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Salir</name>
   <tag></tag>
   <elementGuidId>4eb482e0-5b12-419c-bd7b-f626988d16cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmSignRequired:j_idt835']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Salir&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b47ad6f-ee1c-4771-ba0a-11bec089d1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmSignRequired:j_idt835</value>
      <webElementGuid>5e099a81-cdab-4871-b985-456e1b41c9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmSignRequired:j_idt835</value>
      <webElementGuid>f6ae6ee4-2cde-4f1d-b995-c7b6df27e741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-focus ui-state-hover</value>
      <webElementGuid>31c3e12e-421b-4cab-9656-5e628afb1a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;frmSignRequired:j_idt835&quot;,f:&quot;frmSignRequired&quot;,onco:function(xhr,status,args,data){handleSubmit(xhr,status,args,PF('updateSignHistoria'));;}});return false;</value>
      <webElementGuid>830a60d0-13cb-4908-a061-f0ca594067ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4db742a6-9968-4c61-84de-bb05797ca499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39a24cca-4ec3-4b22-9274-7819e42d254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2e5156fa-fe84-4a38-9fdd-f25bc0aa949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>cbecc8c5-cb0d-484e-b5c5-4aa0b54c8700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmSignRequired:j_idt835&quot;)</value>
      <webElementGuid>c8ccb878-b270-43d2-b3e3-70d38b745f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>56630f3e-d365-4185-8a62-01aa8341b340</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='frmSignRequired:j_idt835']</value>
      <webElementGuid>ecf50274-cdd6-4b1d-9dc3-9186dece01ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSignRequired']/button[2]</value>
      <webElementGuid>bba66298-c2f3-4444-8b5a-dbed197cd229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Desea realizar la firma de la historia para el paciente LUIS NICOLAS AREVALO CHIQUIZA?'])[1]/following::button[2]</value>
      <webElementGuid>b7dced68-3895-4bd9-a33b-6e07ee203050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Firmar Historia'])[1]/preceding::button[1]</value>
      <webElementGuid>6304bdba-1e06-4819-b0cf-1354eba55f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button[2]</value>
      <webElementGuid>ea490678-d7f4-4fd5-8dba-a67be780bfe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'frmSignRequired:j_idt835' and @name = 'frmSignRequired:j_idt835' and @type = 'submit' and (text() = 'Salir' or . = 'Salir')]</value>
      <webElementGuid>38172119-c744-4c0b-85d4-52dce727353b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
