<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Historico                              _9180d6</name>
   <tag></tag>
   <elementGuidId>8f380a38-40a9-451b-9124-71c09dbc19c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='historiaPacienteForm:tabView:acordeonCallHistory:resultadoByFecha']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Historico skip_previous navigate_before navigate_next skip_nextCopiar&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d95598c-bbc3-4d5a-ac3b-24291cab1b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:acordeonCallHistory:resultadoByFecha</value>
      <webElementGuid>a421574b-9c4f-4cdd-a0eb-4d01a12815d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                                
                                                        Historico
                                                                skip_previous
                                                                navigate_before 
                                                                navigate_next
                                                                skip_nextCopiar</value>
      <webElementGuid>0d5d06f4-4fcb-4cab-a49a-9408fff00099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:acordeonCallHistory:resultadoByFecha&quot;)</value>
      <webElementGuid>7291ef16-7f72-4055-8912-35786716fe9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>9bef1a7d-e0f5-4115-83ad-37a8f0a5de6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='historiaPacienteForm:tabView:acordeonCallHistory:resultadoByFecha']</value>
      <webElementGuid>750e405c-814e-4f9f-b075-ce162a721e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='historiaPacienteForm:tabView:acordeonCallHistory:j_idt2255']/div</value>
      <webElementGuid>b288c1a2-1430-4f72-bad5-9b5e89fa1409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historico'])[1]/following::div[2]</value>
      <webElementGuid>603467a1-c0fd-4f02-8591-c875191bad4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[3]/following::div[8]</value>
      <webElementGuid>52987ff7-92b2-4fdd-b3cb-4ff4ba78317f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div</value>
      <webElementGuid>c669fe6b-048a-4468-a828-0f7b313ff537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'historiaPacienteForm:tabView:acordeonCallHistory:resultadoByFecha' and (text() = '                                                
                                                        Historico
                                                                skip_previous
                                                                navigate_before 
                                                                navigate_next
                                                                skip_nextCopiar' or . = '                                                
                                                        Historico
                                                                skip_previous
                                                                navigate_before 
                                                                navigate_next
                                                                skip_nextCopiar')]</value>
      <webElementGuid>eb3ed7c5-e8b1-459a-b004-5c3e965b8d04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
