<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Buscar_historiaPacienteFormtabViewdia_957322</name>
   <tag></tag>
   <elementGuidId>062ea496-a2fb-42e6-a1ea-949888134087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Ingrese texto a Buscar...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49d92c8e-9db1-4433-a997-2bc94e5860d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter</value>
      <webElementGuid>7d774825-c3e5-4b41-8876-f289f332f832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter</value>
      <webElementGuid>685d4d41-e499-4945-b03f-c5c830c0fd1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c24529f8-aac8-4809-8a0c-62962f265806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>4fbc1b0b-e246-4e90-9980-18f49250190c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ingrese texto a Buscar...</value>
      <webElementGuid>91c41030-3f48-4783-bb05-e91755bbdc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>PF('miltitable').filter()</value>
      <webElementGuid>5815d564-fdbf-4623-9e91-04f582eab2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c25bd6b8-bf69-480d-8b25-24657f7e0d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69a5994e-800e-48f4-b2b4-4ac9c706eb7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc82a736-32ac-4f2e-91c6-9bd96d58d6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter&quot;)</value>
      <webElementGuid>0d938330-400d-46d5-a6a2-912fb779be87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>c0293c4c-4efb-439c-8fc5-0e99458d57b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter']</value>
      <webElementGuid>218bc55a-f8a8-4a9e-9969-e36f1f5e895e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:j_idt1660']/input</value>
      <webElementGuid>61ca1aab-f789-4c6c-8612-39787f669af1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div[2]/input</value>
      <webElementGuid>73936506-d6f4-423f-91db-f5c9df4aba16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter' and @name = 'historiaPacienteForm:tabView:diagnosticoComponente:diagnosicoTable:globalFilter' and @type = 'text' and @placeholder = 'Ingrese texto a Buscar...']</value>
      <webElementGuid>d017f39e-3a91-42eb-9d6f-24bf1d0a8661</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
