<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_02-Derivado de consulta externa - via ingreso servicio salud</name>
   <tag></tag>
   <elementGuidId>895530ca-45a3-45d4-a157-b9fe0887570e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;02-	Derivado de consulta externa&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>82adb780-6f67-4dd2-a3e2-3684f93e888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>d04bd368-24cb-432e-a093-9242f24f020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>02-	Derivado de consulta externa</value>
      <webElementGuid>6691cdf6-cd81-4123-bfa0-55f636d5d0cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fc9d5bcd-d74a-49d7-9644-284509a59a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f5245725-f25b-4661-9473-9419e93b4e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>48f34b9f-0235-40d9-90bd-9389b83847c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_2</value>
      <webElementGuid>32665831-f707-4314-b1d0-d68f7aa2c4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>02-	Derivado de consulta externa</value>
      <webElementGuid>8d31db50-baf0-4aaa-9058-68a33f1e6441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_2&quot;)</value>
      <webElementGuid>f6789a5c-9a78-48dd-85e4-ac7bc1c146ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>91888c40-e14b-488f-9af2-e2635cb76292</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_2']</value>
      <webElementGuid>05e2a8db-7e58-4d70-8f8a-d6f5a1efee38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_items']/li[3]</value>
      <webElementGuid>3f3779ce-b7dd-484c-8afe-1905f82f69c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione'])[56]/following::li[2]</value>
      <webElementGuid>e4c661b1-c1ab-4270-b426-d331d96279f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No aplica'])[3]/following::li[3]</value>
      <webElementGuid>781dd78f-2ad7-437b-a0a9-c04c78b2fc65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione uno'])[80]/preceding::li[9]</value>
      <webElementGuid>83b5b3ea-612c-4a15-9d64-a7839a5e98ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[309]/div/ul/li[3]</value>
      <webElementGuid>52d61a65-8902-442f-8af0-6b19e6e16022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'historiaPacienteForm:tabView:diagnosticoComponente:selectViaIngreso_2' and (text() = '02-	Derivado de consulta externa' or . = '02-	Derivado de consulta externa')]</value>
      <webElementGuid>6a0fe49e-3eeb-4593-92ba-9daed02347b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
