<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_15-FinalidadServicio-DIAGNOSTICO</name>
   <tag></tag>
   <elementGuidId>72698578-fdcd-4759-84ee-61d1a538038f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;historiaPacienteForm:tabView:diagnosticoComponente:finalidad_9&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;15-DIAGNOSTICO&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>adcec0cb-9d50-4ac2-a251-385950cdf7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>d96265e3-c735-49a0-bba3-c5afa498f00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>15-DIAGNOSTICO</value>
      <webElementGuid>d21fef88-089a-4286-b2f0-86646523c709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>78616e4d-edc7-4e94-b06c-a694315016b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>0a254d53-b3a9-4d56-8459-1fffe884199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76b29e05-d9dc-4c56-9864-57691205ba9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_5</value>
      <webElementGuid>106731f4-9200-4683-9082-d1825b207764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15-DIAGNOSTICO</value>
      <webElementGuid>8baf15ac-f115-4be0-b30a-4cb0f11ae8ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_5&quot;)</value>
      <webElementGuid>83209fea-9600-4652-b166-f60ce8228139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>a61296ed-e918-4f3d-8f47-0931c325a44b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_5']</value>
      <webElementGuid>7ce92a74-87bc-4e51-8e2d-c84d40d6cd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_items']/li[6]</value>
      <webElementGuid>d6d1067f-cc20-4341-89c1-44adcfcc311e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione uno'])[80]/following::li[5]</value>
      <webElementGuid>aa05d359-ed03-4b45-89c3-b8a3691204ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione'])[55]/following::li[16]</value>
      <webElementGuid>1293a508-62ea-4f00-a2ed-d6d4d6253a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[310]/div/ul/li[6]</value>
      <webElementGuid>96cde568-7f0c-46f0-8dfa-5906be5a8b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_5' and (text() = '15-DIAGNOSTICO' or . = '15-DIAGNOSTICO')]</value>
      <webElementGuid>5c5b2711-4212-4ca0-943f-939642678b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
