<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select-finalidad servicio</name>
   <tag></tag>
   <elementGuidId>85d6a0b8-582a-4ce1-a46b-3208a45dfbf7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;historiaPacienteForm:tabView:diagnosticoComponente:finalidad_label&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;historiaPacienteForm\:tabView\:diagnosticoComponente\:slctFinalidadServicioRipsJsonAp_label&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b2eac775-b0c2-48b1-96ce-fbabcf2eea3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_label</value>
      <webElementGuid>05082fe1-f276-4b44-b4e0-ef4d25379c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>3ba91b95-9dea-4853-8f0f-b8b5250999cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione uno</value>
      <webElementGuid>9595ab5b-b268-4854-8eed-767584301f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_label&quot;)</value>
      <webElementGuid>6794e1ae-5802-474d-86b6-d6f74b0e3f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/CambioEstadoCita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>c186620d-a4b9-401d-abbe-14144bc5d351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_label']</value>
      <webElementGuid>13232579-b800-49d6-b5b1-629237fe665f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp']/label</value>
      <webElementGuid>d36da420-2439-456d-9a00-9e52eab02ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::label[1]</value>
      <webElementGuid>b7f8a489-75b4-498a-a0ad-d0caeff4ccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diagnosticos seleccionados'])[1]/preceding::label[1]</value>
      <webElementGuid>4a3e00e4-8320-4c78-ac4b-c9067d0d32b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='seleccione diagnosticos'])[1]/preceding::label[1]</value>
      <webElementGuid>8c4d2e60-877a-462f-bbe5-adfa6b391cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label</value>
      <webElementGuid>c01f7eba-4c1c-485b-b5c2-f26450b5f4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'historiaPacienteForm:tabView:diagnosticoComponente:slctFinalidadServicioRipsJsonAp_label' and (text() = 'Seleccione uno' or . = 'Seleccione uno')]</value>
      <webElementGuid>11fca362-5adc-424c-97de-b1f74f82d267</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
