<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_agregareliminar cupos del dia</name>
   <tag></tag>
   <elementGuidId>5afcd7e6-a09b-465c-8b8d-da20db486b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form:carrousel:0:j_idt235']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20051b37-4f39-4ed2-8fa9-acc0ceba8168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:carrousel:0:j_idt235</value>
      <webElementGuid>05076bbe-e6a2-4bfc-90e6-50eb5452a013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:carrousel:0:j_idt235</value>
      <webElementGuid>483fdf02-5833-41a7-86d8-e90f6cbc267a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-state-focus ui-state-hover</value>
      <webElementGuid>7a826f30-8551-4d96-a64e-6210a5a9b1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form:carrousel:0:j_idt235&quot;,f:&quot;form&quot;,u:&quot;tabview tabview:addCuposForm&quot;,onco:function(xhr,status,args,data){PF('addCuposWidget').show();}});return false;</value>
      <webElementGuid>b1353524-231e-40fd-9eb0-acbecfc25d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>agregar/eliminar cupos del dia</value>
      <webElementGuid>dde33aa2-50a4-4d13-993c-32f3529e7542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ac6c36ad-9f72-4373-ad77-d08063f9cc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50e1bebb-45bf-4a9a-b6d9-82f0dc64d868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5bf0d99-f653-42c7-bdab-bba11f1da3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>agregar/eliminar cupos del dia</value>
      <webElementGuid>cb955d75-3688-4fdc-aaf5-f347d4c3e987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:carrousel:0:j_idt235&quot;)</value>
      <webElementGuid>ecd74402-2157-4a2a-8738-2df1892691f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>7487d7a5-f482-4612-b72a-7435403d4391</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form:carrousel:0:j_idt235']</value>
      <webElementGuid>f10a6b72-a21c-4726-8464-0f8f8fde5c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='form:carrousel:0:j_idt226']/table/tbody/tr/td[3]/button</value>
      <webElementGuid>7d21e4c3-1304-4de2-a242-71e983a28f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='martes 18-mar.-2025'])[1]/following::button[1]</value>
      <webElementGuid>5cbdc4bf-fcc4-4a7d-9ca8-bacc6a42e644</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NICOLAS AREVALO'])[5]/following::button[1]</value>
      <webElementGuid>1029f6e8-8570-42ba-b553-cb7069844047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bloquear dia/rango'])[1]/preceding::button[1]</value>
      <webElementGuid>5cc768c4-35b8-4e84-acd4-822378a3eb09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button</value>
      <webElementGuid>8f399f93-8c81-4dbc-a368-d7017e963b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'form:carrousel:0:j_idt235' and @name = 'form:carrousel:0:j_idt235' and @title = 'agregar/eliminar cupos del dia' and @type = 'submit' and (text() = 'agregar/eliminar cupos del dia' or . = 'agregar/eliminar cupos del dia')]</value>
      <webElementGuid>1ab6e4de-0e19-4202-a6d5-ec8072e53b17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
