<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceptar</name>
   <tag></tag>
   <elementGuidId>b686bac2-ab01-4dcc-9a53-63f6e2822d81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabview:addCuposForm:btnSave']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1918c8b9-3260-42b1-adf1-3167fd7733a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:btnSave</value>
      <webElementGuid>a48b4436-36a0-4291-b5f4-b3d3c0a3beb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabview:addCuposForm:btnSave</value>
      <webElementGuid>6a17a331-4277-4d48-83bf-be396d61b9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-state-focus ui-state-hover</value>
      <webElementGuid>37bf0780-addc-421f-b0d8-2a3e9337d9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;tabview:addCuposForm:btnSave&quot;,f:&quot;tabview:addCuposForm&quot;,u:&quot;@(#form\\:carrousel :not(.noupdate)) form:growl&quot;,onco:function(xhr,status,args,data){handleSubmit(xhr,status,args,PF('addCuposWidget'));;}});return false;</value>
      <webElementGuid>2913cc18-0b59-4ef0-8101-629a7d69e73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>76e1ac54-ea01-484b-ab8b-aaeed82dbf5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3eb4d776-5fd4-4700-8c48-36a981c3ba07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d829b74-aa16-434a-9037-0808e36d1f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>5aa891bc-06c2-4caa-a821-e0374edf6f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:btnSave&quot;)</value>
      <webElementGuid>fd0a900b-7edf-487b-8a87-98630e68f94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>395c6999-5009-415e-9119-8e216d618921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabview:addCuposForm:btnSave']</value>
      <webElementGuid>065804ef-61f2-48c4-b742-a6300db57375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='tabview:addCuposForm']/div[2]/button</value>
      <webElementGuid>735bbc87-62e2-48b1-b972-275f7a62c7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='on'])[1]/following::button[1]</value>
      <webElementGuid>01d9bc36-a22e-494b-b3ce-901cfc6a0a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='off'])[1]/following::button[1]</value>
      <webElementGuid>4d2a8fa1-0bb4-4545-96c2-d382e24a3a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[12]/preceding::button[1]</value>
      <webElementGuid>2da143b4-7ace-4b67-967f-6cfae2de4faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/form/div[2]/button</value>
      <webElementGuid>94ea6fd6-83a4-4931-af82-d8b4a7425d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'tabview:addCuposForm:btnSave' and @name = 'tabview:addCuposForm:btnSave' and @type = 'submit' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>3814b822-54a7-48b1-8bd2-bbd2ce1b0a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
