<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rango(minutos)_tabviewaddCuposFormrango</name>
   <tag></tag>
   <elementGuidId>d2de535c-9789-4caf-8d92-b42cdf1b6e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tabview:addCuposForm:rango']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;tabview\:addCuposForm\:rango&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>419ab335-0e69-42ff-a7bc-b22f7a2ffcaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:rango</value>
      <webElementGuid>45b65078-95ea-4938-8bea-9129ef52014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabview:addCuposForm:rango</value>
      <webElementGuid>8b7cf043-668d-4989-8fed-b7972fbede4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f64f7ddf-ed28-4b9d-b977-ffcc18ffbedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>7c0ad0b9-b986-4986-938e-8da7d8c2afef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled ui-state-hover ui-state-focus</value>
      <webElementGuid>e174cc5e-eafa-43e9-aac3-59d5c4644852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3daa21a-c769-4f6f-bf68-3e46c9fc3fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;tabview:addCuposForm:rango&quot;,e:&quot;blur&quot;,f:&quot;tabview:addCuposForm&quot;,p:&quot;tabview:addCuposForm:rango&quot;,u:&quot;tabview:addCuposForm:horaInicio&quot;});</value>
      <webElementGuid>695e3754-a0c2-4b07-86d2-24108f619024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e436cb9c-6691-4f32-9e85-a947191fb763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a5e80f16-e6bf-42b6-bb07-054a66ab9b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2b0b691f-d16d-4df4-aa93-f4f5828b83ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:rango&quot;)</value>
      <webElementGuid>062dcd4a-c1cb-4548-a86e-e4bea5756c5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>547876c5-15ff-43a5-b9f7-85cf2a6bd1f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tabview:addCuposForm:rango']</value>
      <webElementGuid>9d136108-fd1d-4df5-b801-e09170de5056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabview:addCuposForm:panelRango']/tbody/tr/td[2]/input</value>
      <webElementGuid>3da80cb6-26ed-49a5-bc5c-f56212ab7e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>cef3a007-7f64-4a82-920d-5872089761f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tabview:addCuposForm:rango' and @name = 'tabview:addCuposForm:rango' and @type = 'text']</value>
      <webElementGuid>d627f375-8be6-440a-bd37-d55cdeffbfe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
