<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rango(minutos)_tabviewaddCuposFormrango</name>
   <tag></tag>
   <elementGuidId>d2de535c-9789-4caf-8d92-b42cdf1b6e2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tabview:addCuposForm:rango']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;tabview\:addCuposForm\:rango&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c12bae11-3ae6-4276-a962-6ec1de5819bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:rango</value>
      <webElementGuid>ff4599c0-907b-4a71-8613-464887d237ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabview:addCuposForm:rango</value>
      <webElementGuid>669cf377-03cf-4cad-bdc2-611792114258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a3e8762a-f1e8-4120-98f1-a5f038099a97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e4eae223-a941-4b49-af58-024b2c3e22eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-filled ui-state-hover ui-state-focus</value>
      <webElementGuid>b24a8044-af24-4633-87ef-ae25da074974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24b641b0-33d7-4496-a441-12953cfd34ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;tabview:addCuposForm:rango&quot;,e:&quot;blur&quot;,f:&quot;tabview:addCuposForm&quot;,p:&quot;tabview:addCuposForm:rango&quot;,u:&quot;tabview:addCuposForm:horaInicio&quot;});</value>
      <webElementGuid>ada99065-a5aa-4d48-b3db-899a88bb4ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e11e8f8f-9c71-43fa-944a-b2f2cdf29e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af4162fd-0f93-451e-8d49-157a960ae6eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11050020-90c9-4484-bdae-0e487fa93363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:rango&quot;)</value>
      <webElementGuid>18abb2d7-ff84-4e85-8f4a-bd7462f3163b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>ad4ed0e5-0159-4e13-980e-e440f51da35d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tabview:addCuposForm:rango']</value>
      <webElementGuid>452d0c3a-57d2-47b6-b3ee-804cb9e68c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabview:addCuposForm:panelRango']/tbody/tr/td[2]/input</value>
      <webElementGuid>988547f7-feb8-407c-8aff-bd1ac3edb707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/input</value>
      <webElementGuid>c60a2ded-5942-4547-a6bd-9a2bbce11334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tabview:addCuposForm:rango' and @name = 'tabview:addCuposForm:rango' and @type = 'text']</value>
      <webElementGuid>b79b014d-1a40-4982-8874-a0eed12f154c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
