<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Tiempo</name>
   <tag></tag>
   <elementGuidId>378b5f21-e981-4140-a18b-efbaa2b963c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='tabview:addCuposForm:tipoRangoCombo_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Tiempo&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a873f36e-e82f-4e22-b3b3-2d6c0f282e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>071a17c2-b41c-4305-9610-054757d89a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Tiempo</value>
      <webElementGuid>88507f8e-9e15-4b78-af40-f71360ec0776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d5523a90-8eb2-4fdd-8469-927b57882bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>cf6a4ac8-f90e-4b60-96f9-5336162a3649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37aed91f-39ad-4925-b118-d35b4751886f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabview:addCuposForm:tipoRangoCombo_1</value>
      <webElementGuid>94fae119-c06b-45ab-8096-0a6d97e96f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiempo</value>
      <webElementGuid>edc29500-9f09-4bc6-8d41-db56d698b01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:tipoRangoCombo_1&quot;)</value>
      <webElementGuid>e4bd838a-0479-4f38-a4df-ada9f7daa1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>1ac817b6-c9a3-43f0-ae73-2f022d8a4316</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='tabview:addCuposForm:tipoRangoCombo_1']</value>
      <webElementGuid>e32404e2-2bea-439b-b9cc-f27ec4d84161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='tabview:addCuposForm:tipoRangoCombo_items']/li[2]</value>
      <webElementGuid>785bb7ca-ca05-440e-9ca9-29a006665cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione'])[56]/following::li[1]</value>
      <webElementGuid>4199f09f-8314-4dfc-b42a-56c28ba0a1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione'])[55]/following::li[2]</value>
      <webElementGuid>17587bd1-41ad-4bc9-82dc-103ca0aca200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SubActividad'])[3]/preceding::li[1]</value>
      <webElementGuid>ba36eb5c-acdb-4902-88d9-9f8eff396857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actividad'])[5]/preceding::li[2]</value>
      <webElementGuid>58941aee-2ca2-4367-90e9-8a23fe2228e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[99]/div/ul/li[2]</value>
      <webElementGuid>74532097-e7a1-49dd-b027-efcc91a6214a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'tabview:addCuposForm:tipoRangoCombo_1' and (text() = 'Tiempo' or . = 'Tiempo')]</value>
      <webElementGuid>3f7b286d-aebd-48b6-9116-f05524d3b989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[163]/div/ul/li[2]</value>
      <webElementGuid>8278146d-6cbf-4a4b-bc2e-38f87110492b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
