<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Seleccione_ui-icon ui-icon-triangle-1-s ui-c_1</name>
   <tag></tag>
   <elementGuidId>a5917d1d-1283-4824-abca-16cebfe71d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabview:addCuposForm:horaInicio']/div[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-selectonemenu-trigger.ui-state-default.ui-corner-right.ui-state-hover > span.ui-icon.ui-icon-triangle-1-s.ui-c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;tabview\:addCuposForm\:horaFinal&quot;] span</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>460ec4e8-e240-4696-819b-a38904a66d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-triangle-1-s ui-c</value>
      <webElementGuid>6b796330-7fb5-4b6b-a48e-296e2505ddd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabview:addCuposForm:horaInicio&quot;)/div[@class=&quot;ui-selectonemenu-trigger ui-state-default ui-corner-right ui-state-hover&quot;]/span[@class=&quot;ui-icon ui-icon-triangle-1-s ui-c&quot;]</value>
      <webElementGuid>f3c4e52c-281c-4d84-9fd5-a7ed2b1a68ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Crear cupos para citas/Page_MedCloud IDL/iframe</value>
      <webElementGuid>34a17cf6-3b74-4cb1-b414-ca5af9fd8113</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabview:addCuposForm:horaInicio']/div[3]/span</value>
      <webElementGuid>a76cf598-ef6f-4a6f-bc2c-14d79697082c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[2]/div/div[3]/span</value>
      <webElementGuid>5dc235a8-eb98-4dd9-9f21-324a2faf060d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabview:addCuposForm:horaFinal']/div[3]/span</value>
      <webElementGuid>cdc9ad52-462e-4967-b786-cbcc79fde31e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td[4]/div/div[3]/span</value>
      <webElementGuid>d130e699-bf6f-4683-9ef8-1da74bf7eb5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
