<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_AceptarFase1</name>
   <tag></tag>
   <elementGuidId>b9b5351b-fbae-4cd1-beb3-b23f484da4ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[span[@class='ui-button-text ui-c' and text()='Aceptar']]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Aceptar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d0dc8ad5-3d55-41be-a95b-0df69815d0aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subactividadesValidationForm:j_idt662</value>
      <webElementGuid>edee39de-02dc-4bd5-86b1-19c39925054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subactividadesValidationForm:j_idt662</value>
      <webElementGuid>2698f617-dcbe-40df-a9d4-8a17c2e6f271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-focus ui-state-hover</value>
      <webElementGuid>0e201a5c-62e5-4c0a-bff3-923d4698b223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;subactividadesValidationForm:j_idt662&quot;,f:&quot;subactividadesValidationForm&quot;,u:&quot;@(form :not(.noupdate))&quot;,onco:function(xhr,status,args,data){handleSubmit(xhr,status,args,PF('validationSubactividadDialog'));;}});return false;</value>
      <webElementGuid>3891ec79-2352-422a-8e42-a7d2b67324e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ba3b48bf-42e1-4f16-9f08-81d2d01f06b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f18106af-4ded-4347-b9e4-872ca8392346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d657395d-98e5-431b-a019-e2ff24888a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>d25394ac-29a4-4f30-b2e5-7bf6cdee7092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subactividadesValidationForm:j_idt662&quot;)</value>
      <webElementGuid>ed7eb088-3afc-4935-b442-d0d5fd150c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>c33f83f7-02cd-487f-96d4-48600dd82e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='subactividadesValidationForm:j_idt662']</value>
      <webElementGuid>253ca98d-c82e-4042-8dc8-1642070c34ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='subactividadesValidationForm']/button</value>
      <webElementGuid>27be0f10-49d8-49f6-8fa1-0d4c8d2d09d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta domiciliaria'])[1]/following::button[1]</value>
      <webElementGuid>80b70b3d-9851-4fae-81c1-803cc3ca1e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videoconsulta'])[1]/following::button[1]</value>
      <webElementGuid>66dff41e-1bcf-4969-921f-40b433e96afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione la subactividad antes de continuar'])[2]/preceding::button[1]</value>
      <webElementGuid>04488c1f-5713-4249-83bd-78d6675a6154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/button</value>
      <webElementGuid>9a616d0f-86c7-4cf3-81ec-866a1e65692c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'subactividadesValidationForm:j_idt662' and @name = 'subactividadesValidationForm:j_idt662' and @type = 'submit' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>51126ba6-86fe-4820-ac48-eb3b094e2dc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
