<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Evolucin historica</name>
   <tag></tag>
   <elementGuidId>eb1c4ae8-a766-4426-97f0-dc26a510319d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='form:carrousel:0:treetableCalendar:4_0:j_idt350']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Evolución historica&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9c9d68fe-b520-4dc5-a6f0-21b37b874035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form:carrousel:0:treetableCalendar:4_0:j_idt350</value>
      <webElementGuid>7a08105e-6e71-45a7-b6ce-1b180e2e929c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form:carrousel:0:treetableCalendar:4_0:j_idt350</value>
      <webElementGuid>44341d33-0112-481c-98f8-d51a90f53642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-icon-only ui-state-focus ui-state-hover</value>
      <webElementGuid>7e584dcc-5bc2-48ff-9581-40128c72fcd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form:carrousel:0:treetableCalendar:4_0:j_idt350&quot;,f:&quot;form&quot;,u:&quot;historicoCitasForm&quot;,onco:function(xhr,status,args,data){PF('historicoCitasWidget').show();}});return false;</value>
      <webElementGuid>8675d233-0ff9-4fcb-b4b1-a6ad33572a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Evolución historica</value>
      <webElementGuid>9f2f229d-ec5d-486b-b4e7-417957d9a6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22f95406-7e5f-42fe-a67c-0415f84ced51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d930d325-d4b3-4e66-8be9-e44a360f8183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ea6a3c9-1fe1-493e-88ea-ecc1b55221d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Evolución historica</value>
      <webElementGuid>f711014e-4b6f-4031-bf1e-13d1d3776d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form:carrousel:0:treetableCalendar:4_0:j_idt350&quot;)</value>
      <webElementGuid>976be058-09aa-41d8-abe5-e1c75b2eb503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>4f6b72a1-51a5-46c1-9aa4-80b7392c6caa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='form:carrousel:0:treetableCalendar:4_0:j_idt350']</value>
      <webElementGuid>72ae8a4c-1e36-4053-af0d-2b617b7e6ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='form:carrousel:0:treetableCalendar_node_4_0']/td/div/button[4]</value>
      <webElementGuid>f89520bb-4ee6-4084-b77b-0f6fffaf2b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado Factura Electrónica'])[1]/following::button[1]</value>
      <webElementGuid>59da093c-d9d5-4091-9f0c-e82000112b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Falta archivo asociado a la cita'])[1]/following::button[2]</value>
      <webElementGuid>2e7761c7-3db9-42bb-912b-8499070fe35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>13fdd5f4-e734-481c-b0b1-6f7507b67b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'form:carrousel:0:treetableCalendar:4_0:j_idt350' and @name = 'form:carrousel:0:treetableCalendar:4_0:j_idt350' and @title = 'Evolución historica' and @type = 'submit' and (text() = 'Evolución historica' or . = 'Evolución historica')]</value>
      <webElementGuid>0d0d5e9a-82ac-40b8-a357-b921bca79b2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
