<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PacienteCrearFormPacienteTabViewcelular</name>
   <tag></tag>
   <elementGuidId>f9b0f2e5-1c5f-4c3f-b329-7a01fbbcd071</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PacienteCrearForm:PacienteTabView:celular']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Celular:*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dd05dbd-f2d4-4d64-a507-8835b291b6ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:celular</value>
      <webElementGuid>6d42e9eb-4ba9-4158-85c5-799401071a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:celular</value>
      <webElementGuid>9b1b7a47-b9cb-4e4c-989c-98f2e7509da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d040923-19ef-46ac-a760-3e7bfe3bd85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>81c55534-aa11-48e0-93c3-e30e55b4b43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c5f2fa28-04f4-406b-9271-7a0c19c0d514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>addd2398-b023-4cbc-9e06-fe353581512f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                          return false;                      }</value>
      <webElementGuid>725718a1-3ae7-4d0f-9a8f-684d9f03965f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputmask ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>71a4cc68-b4e3-45cd-acaf-081e78e0ad05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d4bb0664-29de-448c-85c6-07e1a8141012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e1ec42a-82f6-4bda-8bf8-689e88e88f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>daa68706-0888-47fe-8321-fd752c0e4cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:celular&quot;)</value>
      <webElementGuid>8065cff5-e76b-4890-9412-ae802fb363a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>1b029e42-fb6d-4f16-87fe-3f2b89080f86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PacienteCrearForm:PacienteTabView:celular']</value>
      <webElementGuid>1a3902ba-1f16-4afd-a960-4d2624841d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PacienteCrearForm:PacienteTabView:datBasicos_content']/div[4]/div[4]/input</value>
      <webElementGuid>b6fae16f-e55d-4178-a4c0-905d28d7a6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/input</value>
      <webElementGuid>e96882be-6acf-4ea4-aecd-7ef662a7ebe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PacienteCrearForm:PacienteTabView:celular' and @name = 'PacienteCrearForm:PacienteTabView:celular' and @type = 'text']</value>
      <webElementGuid>96eac0b9-9e2b-4145-9af8-4462ea06c7a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
