<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PacienteCrearFormPacienteTabViewnroI_3c9080</name>
   <tag></tag>
   <elementGuidId>9657d76d-08eb-4e8a-ac89-79e6de911b00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PacienteCrearForm:PacienteTabView:nroIdentificacion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Nro Identificación:*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9849c448-4bbd-4e79-b65f-4bf20914b15b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:nroIdentificacion</value>
      <webElementGuid>a98f3639-adad-469a-9c82-06a0b48df577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:nroIdentificacion</value>
      <webElementGuid>27d4b78b-1183-49cf-b7f4-16fd9b20c0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00ac68cc-4b03-4e7a-b0c1-4271cefbd9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>74169461-2c4b-468a-ba16-4d6ebf666c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77076823-ff51-4338-a5cf-8eb41fc175cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>347707c0-d340-40e8-b555-6df3dd746164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>3add8182-8d98-40fd-8850-508be4604d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Use la tecla TAB para continuar</value>
      <webElementGuid>72692ad3-cf68-4f5c-b367-40a6281ab5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if (event.keyCode === 13) {                              return false;                          }</value>
      <webElementGuid>971472d4-1592-4b34-80bc-2090b83bc5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>PrimeFaces.bcn(this,event,[function(event){PrimeFaces.ab({s:&quot;PacienteCrearForm:PacienteTabView:nroIdentificacion&quot;,e:&quot;blur&quot;,f:&quot;PacienteCrearForm&quot;,p:&quot;PacienteCrearForm:PacienteTabView:nroIdentificacion PacienteCrearForm:PacienteTabView:idTipoIdentificacion&quot;,u:&quot;PacienteCrearForm&quot;});},function(event){PrimeFaces.ab({s:&quot;PacienteCrearForm:PacienteTabView:nroIdentificacion&quot;,e:&quot;blur&quot;,f:&quot;PacienteCrearForm&quot;,p:&quot;PacienteCrearForm:PacienteTabView:nroIdentificacion PacienteCrearForm:PacienteTabView:idTipoIdentificacion&quot;});}])</value>
      <webElementGuid>90298cb9-6960-405a-b0f7-638716757a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>aa0d73ff-85b6-4707-a71e-8d6f7f09e1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e6f3ca8c-039d-4f7c-a79f-beea87da2e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ad011e0c-f145-4afa-9898-569be412a86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:nroIdentificacion&quot;)</value>
      <webElementGuid>92c01cdc-9078-4bc3-a842-d58f7ee2143f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>153155bc-be08-42a0-8986-327b2a260d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PacienteCrearForm:PacienteTabView:nroIdentificacion']</value>
      <webElementGuid>048143ec-3721-40b4-8dd3-605df382dd71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PacienteCrearForm:PacienteTabView:datBasicos_content']/div/div[4]/input</value>
      <webElementGuid>29cf9e3d-3b19-4e02-a202-94d6c77cd0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[4]/input</value>
      <webElementGuid>b10b52f4-b94c-41b7-b23b-4a16908369ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PacienteCrearForm:PacienteTabView:nroIdentificacion' and @name = 'PacienteCrearForm:PacienteTabView:nroIdentificacion' and @type = 'text' and @title = 'Use la tecla TAB para continuar']</value>
      <webElementGuid>aa2116e6-b894-4235-855c-1403b24c247c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
