<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__PacienteCrearFormPacienteTabViewinEps</name>
   <tag></tag>
   <elementGuidId>841d5705-1175-47da-ab3c-bb8d945d5aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PacienteCrearForm:PacienteTabView:inEps']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;EPS:*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4a833c7-ccc9-4fa0-aa0e-3c89af1e255c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:inEps</value>
      <webElementGuid>32208d78-c61c-454b-918d-9d16ac9ab458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:inEps</value>
      <webElementGuid>ecaa9e10-79d1-4ba9-8322-04cd68e45a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25ae8fef-b9e3-472e-ad7c-a2bc2d459358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>1b216d9d-c37e-438a-a06d-e1868a30d73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d575665-b283-4edc-9886-e79a8bd1d053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>288d58ee-4a53-40a3-9f7f-54e5c39fa392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>ab7a6ed3-8044-4144-a5a8-1b9ccb862f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>63e0758c-ac70-44b8-bafa-106c41d9ab10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1ab01dbe-b7c4-4a35-bf32-306bad51a888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b20b16dc-578b-4717-af4b-4922ad4c3a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:inEps&quot;)</value>
      <webElementGuid>535918ac-4b2c-4316-88e2-7c9f8a7e0e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>16ac2342-a1e4-4b0f-ba18-33a67360de8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PacienteCrearForm:PacienteTabView:inEps']</value>
      <webElementGuid>9af9bc4f-a48b-4474-a929-2acb03d74ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PacienteCrearForm:PacienteTabView:datBasicos_content']/div[9]/div[2]/input</value>
      <webElementGuid>f666e7e8-fadd-47fb-9750-af4cff49dcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>04b3f1ac-69f7-4f6e-9cd7-15423feb9084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PacienteCrearForm:PacienteTabView:inEps' and @name = 'PacienteCrearForm:PacienteTabView:inEps' and @type = 'text']</value>
      <webElementGuid>dee9a222-5964-448f-a804-d00dca1453f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
