<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Seleccione uno</name>
   <tag></tag>
   <elementGuidId>d1bc185f-a7a4-4553-91dc-172a130f71e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='PacienteCrearForm:PacienteTabView:idPersonaSexo_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;PacienteCrearForm\:PacienteTabView\:idPersonaSexo_label&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e9a22d5b-cfca-4412-abac-734211261b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:idPersonaSexo_label</value>
      <webElementGuid>c1563308-064e-4c0a-9353-0338ab5ffa59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-label ui-inputfield ui-corner-all</value>
      <webElementGuid>a6d27f98-6d36-4c46-af0b-358383fa2922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione uno</value>
      <webElementGuid>0e5302ab-5bc3-45f7-b462-b6e5d4872e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:idPersonaSexo_label&quot;)</value>
      <webElementGuid>1f1a80bb-81d4-42c4-a866-72df4aaee92f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>a2eff371-b773-4479-8869-1776e337024d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='PacienteCrearForm:PacienteTabView:idPersonaSexo_label']</value>
      <webElementGuid>528c442e-724f-4cf9-855d-b4d72c6ac1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PacienteCrearForm:PacienteTabView:idPersonaSexo']/label</value>
      <webElementGuid>83676143-90e4-4ca9-831b-be809aee86e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::label[1]</value>
      <webElementGuid>8c3135e3-4c2e-41f7-8a6e-1730ed1829c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/preceding::label[1]</value>
      <webElementGuid>980960fc-76b3-4326-823b-d8d4204deadc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div[2]/div/label</value>
      <webElementGuid>1e3bcf43-89d5-4235-a546-2f6b0e16f172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'PacienteCrearForm:PacienteTabView:idPersonaSexo_label' and (text() = 'Seleccione uno' or . = 'Seleccione uno')]</value>
      <webElementGuid>1f00d7bc-1f7e-4898-9065-db62bf6f7906</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
