<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_CIRUGIA PLASTICA-PRIMERA VEZ (120min)</name>
   <tag></tag>
   <elementGuidId>c63eb3d1-ce3d-4297-a1eb-e30f9f6a3cb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='subactividadesValidationForm:subactividadListInterna_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;CIRUGIA PLASTICA-PRIMERA VEZ (120min)&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e0a471fc-5def-4fd6-bd00-d4c7c65d7f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-hover</value>
      <webElementGuid>f432072b-9c4f-4dbe-a66b-a0066a25a474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>CIRUGIA PLASTICA-PRIMERA VEZ (120min) </value>
      <webElementGuid>601b4443-ee5f-4f0b-8b25-99f16c2d08c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>fd4ee299-ac1d-4760-a699-2c18b1e8b5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f728e02b-6799-43e8-9904-87942baec3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa780b37-d836-4996-b510-97ad719baa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>subactividadesValidationForm:subactividadListInterna_4</value>
      <webElementGuid>eeeba28f-e681-4930-82a5-99429c50f182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CIRUGIA PLASTICA-PRIMERA VEZ (120min) </value>
      <webElementGuid>7dfd80b1-fdf9-4d6b-a8ab-39d0d478d8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subactividadesValidationForm:subactividadListInterna_4&quot;)</value>
      <webElementGuid>fd81a15d-d4f6-468a-99de-fdc0d0e0e480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>3e4f2017-fc22-4f0f-8c77-5b1797c2aebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='subactividadesValidationForm:subactividadListInterna_4']</value>
      <webElementGuid>b03b913b-4a4a-4aad-9373-40cd8642eafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='subactividadesValidationForm:subactividadListInterna_items']/li[5]</value>
      <webElementGuid>d8e4f8e9-0b82-409f-b441-5943290182bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIRUGIA PLASTICA-APLICACIÓN BOTOX (60min)'])[2]/following::li[1]</value>
      <webElementGuid>d4a5ac45-5dd0-4c51-b8be-51950f5e566a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIRUGIA PLASTICA-APLI. ACIDO HIALURONICO (60min)'])[2]/following::li[2]</value>
      <webElementGuid>f73bca74-0d5f-46a7-896e-04dd726387c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIRUGIA PLASTICA-CONTROL 1A (60min)'])[2]/preceding::li[1]</value>
      <webElementGuid>b8c6b2d4-7d98-44fb-a08b-027d224a894c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GASTROENTEROLOGIA-COLONOSCOPIA (30min)'])[2]/preceding::li[2]</value>
      <webElementGuid>9bf300d1-7d2e-469c-9db9-4f9b02393b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[171]/div[2]/ul/li[5]</value>
      <webElementGuid>df78c350-8967-4de1-b5ad-05dd8309fbc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'subactividadesValidationForm:subactividadListInterna_4' and (text() = 'CIRUGIA PLASTICA-PRIMERA VEZ (120min) ' or . = 'CIRUGIA PLASTICA-PRIMERA VEZ (120min) ')]</value>
      <webElementGuid>a7f8241f-2370-4944-a811-aaa26b79c662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
