<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Cedula Ciudadania</name>
   <tag></tag>
   <elementGuidId>b62f3f06-cb77-4401-83ef-bc633cea9ba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='PacienteCrearForm:PacienteTabView:idTipoIdentificacion_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;Cedula Ciudadania&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2f76f9e8-754d-44c5-8943-b1959f9dbcff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-selectonemenu-item ui-selectonemenu-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>7719341d-9734-43ab-a926-3a3e0c068d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-label</name>
      <type>Main</type>
      <value>Cedula Ciudadania</value>
      <webElementGuid>da6e2dae-f37a-47b1-b4af-4a5a61d50126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a436c093-6d0f-4361-8bf8-41eb2d2e382a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>018f68b6-9c44-453c-aca5-8efb10fdaf39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e6e4780a-30f7-4f95-8409-d3455dd7790a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:idTipoIdentificacion_4</value>
      <webElementGuid>5bed8ad9-255e-4e6a-8c67-67ceabd34bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cedula Ciudadania</value>
      <webElementGuid>8176ad07-a173-42f4-9ec5-b1115ce2db01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:idTipoIdentificacion_4&quot;)</value>
      <webElementGuid>d4ac0c55-738d-4ce4-863b-d30039f798d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>d9c29b20-44fa-4c69-a638-a316d78aa4dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='PacienteCrearForm:PacienteTabView:idTipoIdentificacion_4']</value>
      <webElementGuid>ba59cb08-0eaf-44da-848e-755713c73776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='PacienteCrearForm:PacienteTabView:idTipoIdentificacion_items']/li[5]</value>
      <webElementGuid>2fee1105-f212-4c7f-8d1f-c846a354ca0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carnet de vacunas'])[3]/following::li[1]</value>
      <webElementGuid>c3616c1e-29a9-4336-911a-3ece251dc3ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carne diplomatico'])[3]/following::li[2]</value>
      <webElementGuid>96c95ffc-3083-452d-ae8e-77b6e0234d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cedula Extranjeria'])[3]/preceding::li[1]</value>
      <webElementGuid>f91f0435-8ade-4470-b75f-203fd9658768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificado nacido vivo'])[3]/preceding::li[2]</value>
      <webElementGuid>e51257ac-bde6-4694-ab0b-1516d7e601a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[143]/div/ul/li[5]</value>
      <webElementGuid>3b6d0c47-df7c-41ac-b85e-23ab613157a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'PacienteCrearForm:PacienteTabView:idTipoIdentificacion_4' and (text() = 'Cedula Ciudadania' or . = 'Cedula Ciudadania')]</value>
      <webElementGuid>0166c50d-d0be-4ad2-addd-6d80f49fa6bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
