<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Seleccione unoAdicionalBeneficiarioC_c24d6b</name>
   <tag></tag>
   <elementGuidId>216c90cc-e9a0-4375-9a14-1d6a5e6f1d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PacienteCrearForm:PacienteTabView:idTipoAfiliado']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tipo Afiliado:*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6fe049df-7a9c-46db-be8f-ca6487154155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:idTipoAfiliado</value>
      <webElementGuid>2d9754a3-2aa8-408e-a194-b11a17d42649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PacienteCrearForm:PacienteTabView:idTipoAfiliado</value>
      <webElementGuid>1989a1db-58af-4b78-ad17-b498836a6719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-1</value>
      <webElementGuid>ca0fac18-b22a-4174-8b04-389f2eb03fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>97d59aa0-b030-4dbf-a732-dbdbcca7553a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	Seleccione uno
	Adicional
	Beneficiario
	Cotizante
	Partícular
</value>
      <webElementGuid>20303844-ca57-4003-bc27-38aeed324cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:PacienteTabView:idTipoAfiliado&quot;)</value>
      <webElementGuid>c7e09eba-7581-449a-9947-56f28c7f4242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>4b432e38-9066-48ce-96ba-3bc82eb30e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PacienteCrearForm:PacienteTabView:idTipoAfiliado']</value>
      <webElementGuid>c9807263-f691-48fa-a608-af3233c6f708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PacienteCrearForm:PacienteTabView:datBasicos2_content']/div[5]/div[2]/select</value>
      <webElementGuid>1f5e5475-334d-41b8-a29b-27a1b5f0894a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[23]/following::select[1]</value>
      <webElementGuid>c25c57aa-6359-47b6-a4ec-055acc50e587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel Educativo:'])[1]/preceding::select[1]</value>
      <webElementGuid>e58e7ed7-4839-406f-9b0c-c68a25c5ca04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remitido Por:'])[1]/preceding::select[2]</value>
      <webElementGuid>f134c799-6c77-4472-8aa9-a6812babfbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>dfd4bc4d-8e94-4048-bf11-eb11cd24a8b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PacienteCrearForm:PacienteTabView:idTipoAfiliado' and @name = 'PacienteCrearForm:PacienteTabView:idTipoAfiliado' and (text() = '	Seleccione uno
	Adicional
	Beneficiario
	Cotizante
	Partícular
' or . = '	Seleccione uno
	Adicional
	Beneficiario
	Cotizante
	Partícular
')]</value>
      <webElementGuid>ed681077-ad08-4813-a165-5b3978a51c7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
