<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aceptar_Resumen_Cita</name>
   <tag></tag>
   <elementGuidId>b87d917a-39f2-4e10-bc84-a7612ecfdfa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='datosCitaForm:j_idt1225']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[id='datosCitaForm:j_idt1225']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Aceptar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a122a29-8af2-4f3b-b1db-a0f370879f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>3be0c185-b37a-4b0e-b00b-e4a6cbe55e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>d4cfc75c-1802-449e-827e-ec51d9cd1a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datosCitaForm:j_idt1066&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>22932e12-9f80-461f-9e4e-bffcff1c691a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>613e84a9-c469-4939-97d4-d1bf120a00b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;datosCitaForm:j_idt1095&quot;]</value>
      <webElementGuid>f436aa53-d6ca-4090-8ef0-4e7dea23c912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='leerle las Recomendaciones al Paciente'])[1]/following::span[1]</value>
      <webElementGuid>eeb792cb-c8ca-4560-bdf1-fabb739289b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUIS NICOLAS AREVALO CHIQUIZA'])[1]/following::span[3]</value>
      <webElementGuid>a87568c3-2301-446f-a2c0-0fd27cdf4ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El cupo ya ha sido usado'])[1]/preceding::span[3]</value>
      <webElementGuid>034af4a4-6dd6-4cad-8166-51c591e57d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[5]/preceding::span[3]</value>
      <webElementGuid>90cff90d-13c2-4f86-aae3-1aa1c929bc63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center[2]/button/span</value>
      <webElementGuid>b5d4264b-4b11-4ab8-8a70-c980cbac9157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>b28d4a58-482e-4096-8f4c-516d0030e7b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
