<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Guardar</name>
   <tag></tag>
   <elementGuidId>2262a8e1-772e-4e46-8c3a-54df30803ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='PacienteCrearForm:savebtn']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot; Guardar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4009f93b-8c13-4080-96aa-d20ce2f0f795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>70f518b9-0ae4-4f37-ab49-df616a2e6b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar</value>
      <webElementGuid>00cd2259-e776-4147-adbc-cd252e899198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PacienteCrearForm:savebtn&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>21ee620f-99c3-48ee-a2a3-5f29ed4fa9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>7551bba5-7509-4f23-b908-48fece295bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='PacienteCrearForm:savebtn']/span[2]</value>
      <webElementGuid>5e63ee7b-4383-4f94-901e-0e6cd3cb601c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EPS:'])[1]/following::span[2]</value>
      <webElementGuid>9513b87a-01db-40ba-9216-51bd2e9ff1f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[15]/preceding::span[2]</value>
      <webElementGuid>cbf1f8ca-c2e2-43bc-b666-608fa0542015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[16]/preceding::span[3]</value>
      <webElementGuid>7e9ede4d-f657-4d40-b5cb-0c7e81dcab02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button[2]/span[2]</value>
      <webElementGuid>ace95baf-563e-437f-b1a2-b594e7a166c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Guardar' or . = 'Guardar')]</value>
      <webElementGuid>fa7e52d1-28ec-4b3a-b081-6ac7870d109e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
