<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aceptar</name>
   <tag></tag>
   <elementGuidId>027d8a8e-680e-4b82-9ba5-ec32952a7d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='subactividadesValidationForm:j_idt651']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Aceptar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4bd2bb0e-fd4f-4637-a2e7-a741f9e652dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>bdc57ccd-c344-439f-8a94-78f15aad662a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>efe163a5-e19a-4131-b2c1-e2fa615bdf60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subactividadesValidationForm:j_idt651&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>cddd36c9-f2af-4529-a926-bfae648a3d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/crecion cita/Page_MedCloud IDL/iframe</value>
      <webElementGuid>91a76d91-1594-4598-a07d-1ce7ff80cf04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='subactividadesValidationForm:j_idt651']/span</value>
      <webElementGuid>8c2061ed-c6e2-4930-a861-36c35fae5f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta domiciliaria'])[1]/following::span[1]</value>
      <webElementGuid>1d81f399-9b81-4097-aadc-81fae5ba51c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videoconsulta'])[1]/following::span[2]</value>
      <webElementGuid>6c4349d9-f500-4d74-833b-565bdac167f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione la subactividad antes de continuar'])[2]/preceding::span[5]</value>
      <webElementGuid>904e9ea6-b20e-4372-b4ee-a9deab5231d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione'])[15]/preceding::span[6]</value>
      <webElementGuid>fbf33c8d-790d-43fa-9cba-f80e03b62158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>25538d22-f54c-4726-b793-44f69fe1d038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/button/span</value>
      <webElementGuid>05c4f6ae-56b9-4bc6-89a5-545385c28d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>216648da-041c-42f0-b418-53ec29f60e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='subactividadesValidationForm:j_idt650']/span</value>
      <webElementGuid>061652d3-e6a0-460a-a61d-0c428e131ec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
