<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Guardar Como Plantilla</name>
   <tag></tag>
   <elementGuidId>7f363e69-dc17-4e82-8223-19194ea6682d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='historiaPacienteForm:tabView:editorComponente:btnGuardar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31b5cef0-320d-47ea-be83-e0da31547826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:editorComponente:btnGuardar</value>
      <webElementGuid>ccd383dd-9b78-4aae-b496-4e08b7f5418c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>historiaPacienteForm:tabView:editorComponente:btnGuardar</value>
      <webElementGuid>9cb4f121-1cfc-4b13-98f6-2450c19baec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left ui-state-focus ui-state-hover</value>
      <webElementGuid>f0df036f-ce86-4e90-8fa4-4a04477419f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;historiaPacienteForm:tabView:editorComponente:btnGuardar&quot;,f:&quot;historiaPacienteForm&quot;,u:&quot;savePlantillaForm&quot;,rv:true});return false;</value>
      <webElementGuid>b24606cf-d73f-442e-919c-7518bca4af5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ec954351-4325-4a42-a108-203e13d5531d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df3c9592-bb2b-4918-a087-6d988bf19bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f43434db-8055-4a7b-9bd1-a3147e9e9675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Guardar Como Plantilla</value>
      <webElementGuid>c60bbaef-1b42-4e21-9929-820cc812ad5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;historiaPacienteForm:tabView:editorComponente:btnGuardar&quot;)</value>
      <webElementGuid>d655a570-23ca-4b2c-8f51-6b6c47964c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='historiaPacienteForm:tabView:editorComponente:btnGuardar']</value>
      <webElementGuid>22536799-9889-4d11-a675-f8a69611b1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='historiaPacienteForm:tabView:dataComponentes']/button</value>
      <webElementGuid>09fc119f-fc2f-42c5-9b3d-c116335bbfd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='div'])[1]/following::button[1]</value>
      <webElementGuid>254d4be8-a59e-4ba8-a3d8-d909863718ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='body'])[1]/following::button[1]</value>
      <webElementGuid>4d92fd02-3dfc-4825-bac6-3e7d6acec914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historico'])[1]/preceding::button[1]</value>
      <webElementGuid>db06688b-cf84-4bcc-9156-88001c9d1c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>dea67eac-010e-461e-bf81-62c54df8021b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'historiaPacienteForm:tabView:editorComponente:btnGuardar' and @name = 'historiaPacienteForm:tabView:editorComponente:btnGuardar' and @type = 'submit' and (text() = 'Guardar Como Plantilla' or . = 'Guardar Como Plantilla')]</value>
      <webElementGuid>b3a8530d-80d6-43df-bdf7-bbf5f15434bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
