<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_settings</name>
   <tag></tag>
   <elementGuidId>a6aba1f4-4df0-4158-b810-59eb15e6a6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='j_idt84']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#j_idt84 > a.ripplelink.tabmenuitem-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;settings&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2c0ee609-b703-4d1b-ad1e-3afbd65e1e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>264be9d8-58fe-46ab-88c0-91c9cfc78c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ripplelink tabmenuitem-link</value>
      <webElementGuid>f07fe2f6-4f0c-42d6-a70a-1444c6f61252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>settings</value>
      <webElementGuid>a71df515-fab1-41ea-a590-717aee28322c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt84&quot;)/a[@class=&quot;ripplelink tabmenuitem-link&quot;]</value>
      <webElementGuid>bace4b4c-e328-4c3f-87e2-b184a69b0189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/inicio sesion/Page_MedCloud IDL/iframe</value>
      <webElementGuid>8ef926c5-d116-4a6f-9480-fd836d945019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='j_idt84']/a</value>
      <webElementGuid>ade30727-fa55-4d60-bf68-0f221eee6903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDL INGENIERIA DE DESARROLLO SAS'])[1]/following::a[1]</value>
      <webElementGuid>9b10ed0f-5fba-4bb9-a81e-b7ee7fed17fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='home'])[1]/following::a[1]</value>
      <webElementGuid>30969b58-2ef5-48d8-aca7-171b08d1735c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medcloud Menú'])[1]/preceding::a[1]</value>
      <webElementGuid>ef6f0519-ee1b-42dd-89b8-6d440e0ccc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>6efae7f2-f568-4112-b5ef-3628854cfeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>f51c6f6a-fa59-4d27-9391-0622ad9f23e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'settings' or . = 'settings')]</value>
      <webElementGuid>16438d2c-754d-4b82-8c95-f8d7eb96c6fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
